import type { Metadata } from "next";
import "./globals.css";
import { Epilogue } from "next/font/google";
import Navbar from "../components/nav";
import Footer from "@/components/footer";

const epilogue = Epilogue({
	variable: "--font-epilogue",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${epilogue.variable}  antialiased`}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
